spring:
  datasource:
    url: jdbc:postgresql://${prod_db_host}:${prod_db_port}/${prod_db_name}
    username: ${postgres_prod_username}
    password: ${postgres_prod_password}
    driver-class-name: org.postgresql.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       format_sql: true
  #   database: postgresql
  #   database-platform: org.hibernate.dialect.PostgreSQLDialect
